name: taco_party
description: A hypnotic cascade of images. Good for all occasions.
version: 2.1.2
author: Kai Page <kaibug@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  archive: ^2.0.4

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
