name: taco_party
description: A hypnotic cascade of images. Good for all occasions.
version: 3.0.0
author: Kai Page <kaibug@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  archive: ^2.0.5
  angular: ^5.2.0
  angular_router: ^2.0.0-alpha
  sass_builder: ^2.1.2
  http: ^0.12.0
  yaml: ^2.1.15
  stream_transform: ^0.0.14
  angular_forms: ^2.1.1
  color: ^2.1.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0

  # mostly here to stop the build from complaining, apparently angular wants me to actually test my code
  test: ^1.5.1
