name: taco_party
description: You ever wanted some Tacos?
version: 0.0.1
author: Kai Page <kaibug@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
